-- MySQL Script generated by MySQL Workbench
-- Thu Aug 27 09:50:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `usuario_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario_app` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL COMMENT 'sindico\nprestador\nvistoriador',
  `remember_token` TEXT NULL,
  `token_noification` TEXT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afiliado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(255) NOT NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `cartao_cnpj` VARCHAR(255) NULL DEFAULT NULL,
  `inscricao_estadual` VARCHAR(45) NULL DEFAULT NULL,
  `inscricao_municipal` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(8) NULL DEFAULT NULL,
  `estado` VARCHAR(80) NULL DEFAULT NULL,
  `cidade` VARCHAR(80) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `rua` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(11) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `ramo_atividade` VARCHAR(255) NULL DEFAULT NULL,
  `numero_funcionarios` INT(11) NULL DEFAULT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'pendente' COMMENT 'pendente\nativo\ninativo',
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `usuario_app_id` INT NOT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `data_contrato` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_afiliados_usuario_app1_idx` (`usuario_app_id` ASC),
  CONSTRAINT `fk_afiliados_usuario_app1`
    FOREIGN KEY (`usuario_app_id`)
    REFERENCES `usuario_app` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 212
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `nome` VARCHAR(255) NOT NULL,
  `imagem_principal` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` LONGTEXT NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'publicado' COMMENT 'publicado\nrascunho',
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `chave_url` TEXT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `ativo` INT NOT NULL DEFAULT 1,
  `imagem` TEXT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 80
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `logErroEmail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logErroEmail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dataErro` DATETIME NULL DEFAULT NULL,
  `mensagemErro` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `logSendinBlue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logSendinBlue` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dataCriacao` DATETIME NULL DEFAULT NULL,
  `idOrcamento` INT(11) NULL DEFAULT NULL,
  `retorno` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7436
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `parceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parceiros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome_responsavel` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(11) NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'pendente' COMMENT 'ativo\npendente\ninativo',
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `usuario_sistema_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario_sistema_admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `status` INT(11) NOT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `tipo` VARCHAR(45) NOT NULL COMMENT 'superadmin\nadmin',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regiao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plano_disponivel_franqueado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plano_disponivel_franqueado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Aqu ficarão os plaos que os franqueados poderão disponibilizar para seus afiliados',
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(50) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `valor_comissao` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `statusPlano` INT(11) NOT NULL,
  `quantidade_meses_vigencia` INT NOT NULL,
  `dias_trial` INT NOT NULL DEFAULT 0,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `usuario_sistema_admin_id` INT(11) NOT NULL,
  `regiao_id` INT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_plano_disponivel_franqueado_usuario_sistema_admin1_idx` (`usuario_sistema_admin_id` ASC),
  INDEX `fk_plano_disponivel_franqueado_regiao1_idx` (`regiao_id` ASC),
  CONSTRAINT `fk_plano_disponivel_franqueado_usuario_sistema_admin1`
    FOREIGN KEY (`usuario_sistema_admin_id`)
    REFERENCES `usuario_sistema_admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plano_disponivel_franqueado_regiao1`
    FOREIGN KEY (`regiao_id`)
    REFERENCES `regiao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `responsavel_afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `responsavel_afiliado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `numero_documento` INT(11) NULL DEFAULT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cargo` VARCHAR(255) NULL DEFAULT NULL,
  `afiliado_id` INT(11) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_responsavelAfiliado_afiliados1_idx` (`afiliado_id` ASC),
  CONSTRAINT `fk_responsavelAfiliado_afiliados1`
    FOREIGN KEY (`afiliado_id`)
    REFERENCES `afiliado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 222
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sessaoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sessaoUsuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  `inicioSessao` DATETIME NULL DEFAULT NULL,
  `fimSessao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1012
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vistoriador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vistoriador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_app_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_vistoriador_usuario_app1_idx` (`usuario_app_id` ASC),
  CONSTRAINT `fk_vistoriador_usuario_app1`
    FOREIGN KEY (`usuario_app_id`)
    REFERENCES `usuario_app` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sindico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sindico` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `numero_documento` INT(11) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `usuario_app_id` INT NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_sindico_usuario_app1_idx` (`usuario_app_id` ASC),
  CONSTRAINT `fk_sindico_usuario_app1`
    FOREIGN KEY (`usuario_app_id`)
    REFERENCES `usuario_app` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 222
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `condominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `condominio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(255) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `sindico_id` INT(11) NOT NULL,
  `regiao_id` INT NOT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_condominio_sindico1_idx` (`sindico_id` ASC),
  INDEX `fk_condominio_regiao1_idx` (`regiao_id` ASC),
  CONSTRAINT `fk_condominio_sindico1`
    FOREIGN KEY (`sindico_id`)
    REFERENCES `sindico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_condominio_regiao1`
    FOREIGN KEY (`regiao_id`)
    REFERENCES `regiao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9554
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  `status` INT(1) NULL,
  `status_sindico` INT(1) NULL,
  `status_afiliado` INT(1) NULL,
  `condominio_id` INT(11) NOT NULL,
  `afiliado_id` INT(11) NULL,
  `categoria_id` INT(11) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_orcamento_condominio1_idx` (`condominio_id` ASC),
  INDEX `fk_orcamento_afiliados1_idx` (`afiliado_id` ASC),
  INDEX `fk_orcamento_categorias1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_orcamento_condominio1`
    FOREIGN KEY (`condominio_id`)
    REFERENCES `condominio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orcamento_afiliados1`
    FOREIGN KEY (`afiliado_id`)
    REFERENCES `afiliado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orcamento_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vistoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vistoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `data_vistoria` TIMESTAMP NOT NULL,
  `data_checkout` TIMESTAMP NULL,
  `data_checkin` TIMESTAMP NULL,
  `vistoriador_id` INT NOT NULL,
  `orcamento_id` INT NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `latitude_checkin` DOUBLE NULL,
  `longitude_checkin` DOUBLE NULL,
  `latitude_checkout` DOUBLE NULL,
  `latitude_checkout` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vistoria_vistoriador1_idx` (`vistoriador_id` ASC),
  INDEX `fk_vistoria_orcamento1_idx` (`orcamento_id` ASC),
  CONSTRAINT `fk_vistoria_vistoriador1`
    FOREIGN KEY (`vistoriador_id`)
    REFERENCES `vistoriador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vistoria_orcamento1`
    FOREIGN KEY (`orcamento_id`)
    REFERENCES `orcamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vistoria_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vistoria_imagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vistoria_id` INT NOT NULL,
  `descricao` TEXT NULL,
  `caminho_imagem` TEXT NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacvao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_imagem_vistoria1_idx` (`vistoria_id` ASC),
  CONSTRAINT `fk_imagem_vistoria1`
    FOREIGN KEY (`vistoria_id`)
    REFERENCES `vistoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afiliado_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afiliado_categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `afiliado_id` INT(11) NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  INDEX `fk_afiliados_has_categorias_categorias1_idx` (`categoria_id` ASC),
  INDEX `fk_afiliados_has_categorias_afiliados1_idx` (`afiliado_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_afiliados_has_categorias_afiliados1`
    FOREIGN KEY (`afiliado_id`)
    REFERENCES `afiliado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_afiliados_has_categorias_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `franqueado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `franqueado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `token_asaas_producao` TEXT NULL,
  `token_asaas_debug` TEXT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `inscricao_estadual` VARCHAR(45) NULL,
  `inscricao_municipal` VARCHAR(45) NULL,
  `cpf_responsavel` VARCHAR(45) NULL,
  `rg_responsavel` VARCHAR(45) NULL,
  `profissao_responsavel` VARCHAR(45) NULL,
  `telefone_responsavel` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `franqueado_regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `franqueado_regiao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `franqueado_id` INT NOT NULL,
  `regiao_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'ativo' COMMENT 'inativo',
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `data_inicio_atividade` DATE NULL,
  `data_fim_atividade` DATE NULL,
  `usuario_sistema_admin_id` INT(11) NOT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  INDEX `fk_franqueado_has_regiao_regiao1_idx` (`regiao_id` ASC),
  INDEX `fk_franqueado_has_regiao_franqueado1_idx` (`franqueado_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_franqueado_regiao_usuario_sistema_admin1_idx` (`usuario_sistema_admin_id` ASC),
  CONSTRAINT `fk_franqueado_has_regiao_franqueado1`
    FOREIGN KEY (`franqueado_id`)
    REFERENCES `franqueado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_franqueado_has_regiao_regiao1`
    FOREIGN KEY (`regiao_id`)
    REFERENCES `regiao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_franqueado_regiao_usuario_sistema_admin1`
    FOREIGN KEY (`usuario_sistema_admin_id`)
    REFERENCES `usuario_sistema_admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `franqueado_regiao_plano_disponibilizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `franqueado_regiao_plano_disponibilizado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `franqueado_regiao_id` INT NOT NULL,
  `plano_disponivel_franqueado_id` INT(11) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  INDEX `fk_franqueado_regiao_has_plano_disponivel_franqueado_plano__idx` (`plano_disponivel_franqueado_id` ASC),
  INDEX `fk_franqueado_regiao_has_plano_disponivel_franqueado_franqu_idx` (`franqueado_regiao_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_franqueado_regiao_has_plano_disponivel_franqueado_franquea1`
    FOREIGN KEY (`franqueado_regiao_id`)
    REFERENCES `franqueado_regiao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_franqueado_regiao_has_plano_disponivel_franqueado_plano_di1`
    FOREIGN KEY (`plano_disponivel_franqueado_id`)
    REFERENCES `plano_disponivel_franqueado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plano_assinatura_afiliado_regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plano_assinatura_afiliado_regiao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Aqu ficarão os plaos que os franqueados poderão disponibilizar para seus afiliados',
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(50) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `valor_comissao` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `statusPlano` INT(11) NOT NULL,
  `quantidade_meses_vigencia` INT NOT NULL,
  `dias_trial` INT NOT NULL DEFAULT 0,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `franqueado_regiao_plano_disponibilizado_id` INT NOT NULL,
  `data_pagamento` TIMESTAMP NULL,
  `data_cancelamento` TIMESTAMP NULL,
  `data_expiracao` DATE NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_plano_disponibilizado_franqueado_franqueado_regiao_plano_idx` (`franqueado_regiao_plano_disponibilizado_id` ASC),
  CONSTRAINT `fk_plano_disponibilizado_franqueado_franqueado_regiao_plano_d1`
    FOREIGN KEY (`franqueado_regiao_plano_disponibilizado_id`)
    REFERENCES `franqueado_regiao_plano_disponibilizado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afiliado_regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afiliado_regiao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `afiliado_id` INT(11) NOT NULL,
  `regiao_id` INT NOT NULL,
  `data_pagamento_plano` TIMESTAMP NULL,
  `data_expiracao_plano` DATE NULL,
  `plano_assinatura_afiliado_regiao_id` INT(11) NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  INDEX `fk_afiliados_has_regiao_regiao1_idx` (`regiao_id` ASC),
  INDEX `fk_afiliados_has_regiao_afiliados1_idx` (`afiliado_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_afiliado_regiao_plano_assinatura_afiliado_regiao1_idx` (`plano_assinatura_afiliado_regiao_id` ASC),
  CONSTRAINT `fk_afiliados_has_regiao_afiliados1`
    FOREIGN KEY (`afiliado_id`)
    REFERENCES `afiliado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_afiliados_has_regiao_regiao1`
    FOREIGN KEY (`regiao_id`)
    REFERENCES `regiao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_afiliado_regiao_plano_assinatura_afiliado_regiao1`
    FOREIGN KEY (`plano_assinatura_afiliado_regiao_id`)
    REFERENCES `plano_assinatura_afiliado_regiao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `imagem_orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imagem_orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NULL,
  `caminho_imagem` TEXT NOT NULL,
  `orcamento_id` INT NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_imagem_orcamento_orcamento1_idx` (`orcamento_id` ASC),
  CONSTRAINT `fk_imagem_orcamento_orcamento1`
    FOREIGN KEY (`orcamento_id`)
    REFERENCES `orcamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contrato_social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contrato_social` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` VARCHAR(45) NOT NULL DEFAULT 'pendente' COMMENT 'pendente\naceito\nrecusado',
  `arquivo` LONGBLOB NOT NULL,
  `afiliado_id` INT(11) NOT NULL,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_contrato_social_afiliados1_idx` (`afiliado_id` ASC),
  CONSTRAINT `fk_contrato_social_afiliados1`
    FOREIGN KEY (`afiliado_id`)
    REFERENCES `afiliado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartao_cnpj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartao_cnpj` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` VARCHAR(45) NOT NULL DEFAULT 'pendente' COMMENT 'pendente\naceito\nrecusado',
  `arquivo` LONGBLOB NOT NULL,
  `afiliado_id` INT(11) NOT NULL,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_contrato_social_afiliados1_idx` (`afiliado_id` ASC),
  CONSTRAINT `fk_contrato_social_afiliados10`
    FOREIGN KEY (`afiliado_id`)
    REFERENCES `afiliado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` VARCHAR(45) NOT NULL DEFAULT 'pendente' COMMENT 'pendente\naceito\nrecusado',
  `arquivo` LONGBLOB NOT NULL,
  `afiliado_id` INT(11) NOT NULL,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_contrato_social_afiliados1_idx` (`afiliado_id` ASC),
  CONSTRAINT `fk_contrato_social_afiliados11`
    FOREIGN KEY (`afiliado_id`)
    REFERENCES `afiliado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `chave` VARCHAR(80) NOT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `estado_id` INT NOT NULL,
  `chave` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `cidade_id` INT NOT NULL,
  `chave` VARCHAR(150) NOT NULL,
  `regiao_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bairro_cidade1_idx` (`cidade_id` ASC),
  INDEX `fk_bairro_regiao1_idx` (`regiao_id` ASC),
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bairro_regiao1`
    FOREIGN KEY (`regiao_id`)
    REFERENCES `regiao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rua` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `cep` VARCHAR(8) NOT NULL,
  `bairro_id` INT NOT NULL,
  `chave` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rua_bairro1_idx` (`bairro_id` ASC),
  CONSTRAINT `fk_rua_bairro1`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `afiliado_orcamento_interesse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afiliado_orcamento_interesse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `afiliado_id` INT(11) NOT NULL,
  `orcamento_id` INT NOT NULL,
  `interessado` INT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `ativo` INT(1) NOT NULL DEFAULT 1,
  `nao_interessante` INT(1) NOT NULL DEFAULT 0,
  INDEX `fk_afiliado_has_orcamento_orcamento1_idx` (`orcamento_id` ASC),
  INDEX `fk_afiliado_has_orcamento_afiliado1_idx` (`afiliado_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_afiliado_has_orcamento_afiliado1`
    FOREIGN KEY (`afiliado_id`)
    REFERENCES `afiliado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_afiliado_has_orcamento_orcamento1`
    FOREIGN KEY (`orcamento_id`)
    REFERENCES `orcamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
